name: Rust

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SHAHOW_TOKEN }}
        with:
          tag_name: v0.1.1
          release_name: v0.1.1
          draft: false
          prerelease: false
      - name: upload url
        id: upload url
        run: echo ${{ steps.create_release.outputs.upload_url }}
